### ISSUE TITLE
Fehler beim setzen eines externen Links

### ISSUE THREAD

**Issue by brandes-webdesign** [FriendsOfREDAXO/tinymce#104]
Wenn ich im Text einen externen Link setze, dann wird das nicht übernommen, also das href ist dann weg und somit der Link nicht vorhanden. 

Interne Links klappen.

REDAXO: 5.17.1
PHP: 8.2
Database: MariaDB 10.6.18
Browser: Firefox
AddOns: TinyMce (neuste Version)

**Comment by KERERCVASD** [comment]
This might help:This file might fix it

https://mega.nz/file/1vkGlJTL#yU-SJLlIilF0mx5qwpPOd3BM8iKZqOJLEQUStR76rrQ
If you don't have the c compliator, install it.(gcc or clang)

**Comment by brandes-webdesign** [comment]
Noch eine Zusatzinfo, die vielleicht schon die Lösung ist ?

Ich habe 2 Domains in einem Redaxo mit yRewrite.
Und ich wollte die Domains untereinander verlinken und hab dann halt www.domain2.de als externer Link versucht.

Hab es eben mal anders als internen Link versucht und da klappt es und im Frontend wird www.domain2.de gesetzt.
Die EIngabe im Backend ist aber so: redaxo://271

Anscheinend biegt das yRewrite dann richtig um in dem Fall.

Ist vielleicht in der Konstellation nur einen Denkfehler von mir ?.

**Comment by tbaddade** [comment]
Alle Artikel die innerhalb der Instanz vorhanden sind, egal über welcher Domain die laufen, sind interne Artikel und sollte auch über die Linkmap ausgewählt werden.

YRewrite setzt die Urls dann mit der korrekten Domain zusammen.

**Comment by brandes-webdesign** [comment]
Also doch ein Denk- / Benutzerfehler bei mir.
DANKE für Deine Hilfe.

**Comment by brandes-webdesign** [comment]
Hab eben geschaut.
Ein externer Link zu einer anderen Domain klappt einwandfrei. 

Das kann hier also geschlossen werden.
SORRY für die Arbeit.
