### ISSUE TITLE
dark-mode

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/tinymce#35]
https://www.tiny.cloud/blog/dark-mode-tinymce-rich-text-editor/

Nützlich dafür Können auch folgende Stellen im CKE5 sein: 

https://github.com/FriendsOfREDAXO/cke5/blob/955c331c56c7e7af59702f398f4fb66995ef7065/assets/cke5.js#L13-L31

https://github.com/FriendsOfREDAXO/cke5/blob/955c331c56c7e7af59702f398f4fb66995ef7065/boot.php#L15-L31

**Comment by TobiasKrais** [comment]
Eventuell ist der PR interessant:  https://github.com/redaxo/redaxo/pull/5025

**Comment by skerbis** [comment]
ist zu 90% die selbe Lösung wie ich in CKE5 realisiert habe. Meine Lösung ist rückwärtskompatibel

**Comment by skerbis** [comment]
Darkmode in 6 geht so: 

```js
skin: (window.matchMedia(“(prefers-color-scheme: dark)“).matches ? “oxide-dark” : “”),
content_css: (window.matchMedia(“(prefers-color-scheme: dark)“).matches ? “dark” : “”),
```
