### ISSUE TITLE
Verlinkung zu einer Yform Tabelle

### ISSUE THREAD

**Issue by steri-rex** [FriendsOfREDAXO/tinymce#46]
Kann man in Tinymce5 sowie in Tinymce4 eine Verlinkung zu einer Yform Tabelle machen? Bei Tinymce4 konnte man im Profil von Tinymce dies ergänzen
tables: 'rex_table_1[fields:field_1+field_2,filter:field_status=1,order:field_1],
das scheint in Tinymce5 nicht mehr zu funktionieren.

**Comment by eaCe** [comment]
Das sollte in der aktuellen Github Version möglich sein.

**Comment by alxndr-w** [comment]
https://github.com/FriendsOfREDAXO/tinymce/tree/master/custom_plugins/link_yform
