### ISSUE TITLE
Duplicate entry beim Duplizieren eines Profils

### ISSUE THREAD

**Issue by clausbde** [FriendsOfREDAXO/tinymce#49]
**Description / Beschreibung**
Beim Duplizieren eines Profils bekomme ich eine Rückmeldung
rex_tinymce5_profiles_clone_exception

Im Log steht dann (beim Kopieren des Profils light):
Duplicate entry 'light' for key 'name'

Es wird also kein neuer Name gebildet (oder hat sich die Tabelle geändert und name ist jetzt eine unique-Spalte?)

**Affected versions / Verwendete Versionen**
Version 1.2.17

**Comment by dtpop** [comment]
Wird für tinymce6 gefixt.
