### ISSUE TITLE
Kein forced_root_block: false mehr in in TinyMCE 6 :-(

### ISSUE THREAD

**Issue by dtpop** [FriendsOfREDAXO/tinymce#59]
Es ist keine gute Nachricht: TinyMCE 6 hat die Konfiguration forced_root_block: false gestrichen.
Man kann das hier nachlesen: https://github.com/tinymce/tinymce/discussions/7342
Da dies eines der wichtigen Features und Gründe für die Verwendung dieses Editors war (wie auch in der Diskussion zu lesen ist), kann momentan ein Umstieg auf die Version 6 nicht uneingeschränkt empfohlen werden. Daher bleibt der beta Status erstmal erhalten, auch wenn das Addon selbst sonst gut läuft.

**Comment by skerbis** [comment]
Sehe hier kein Problem. P durch br zu ersetzen ist ein no-go.

**Comment by alexwenz** [comment]
Wir verwenden den Editor auch, um dem Nutzer Eingaben in Bereichen zu ermöglichen, wo kein <p> erwünscht ist. z.B. Headlines, Anlesetexte etc. Hier wird der Output mit dem block-level-Tag umgeben. 

So hat der Nutzer im Editor aber weiterhin die Möglichkeit, lang-Attribute zu setzen, mit &shy; Umbrüche an gewünschten Stellen hinzuzufügen, Links einzubauen (im Anlesetext), auf die Sonderzeichen-Liste zurückzugreifen und ggf. em/b.-Markierungen einzufügen.

**Comment by tbaddade** [comment]
> P durch br zu ersetzen ist ein no-go.

Sehe ich nicht so. 
Manchmal benötigt man tatsächlich einen weichen Umbruch. 

@dtpop Ich kenne den Tiny nicht, aber im Redactor wird auf `enter` ein `<p>` erstellt und auf ein `control`+ `enter` ein `<br>` (weicher Umbruch).

Eventuell lässt sich damit das Problem beheben.

**Comment by skerbis** [comment]
> Ich kenne den Tiny nicht, aber im Redactor wird auf enter ein <p> erstellt und auf ein control+ enter ein <br> (weicher Umbruch).
Das ist auch im Tiny und anderen Editoren so. Es geht hier darum, dass ein Wrapper-Container erzwungen wird, bei Tiny ist es p. Und das sich Tiny als HTML-Editor versteht, hält er sich an der Konvention zumindest einen Container einzusetzen. Soweit ich die Diskussion bei Tiny verfolgen konnte, scheint es aber möglich anstelle eines p, z.B. ein DIV zu erzwingen.

**Comment by skerbis** [comment]
Doofe Frage, aber wie kommt bei Dir `<h2><span>Jetzt kommt der Text aus Tiny</span></h2>`zustande?

**Comment by alexwenz** [comment]
Im Ausgabemodul wird 

`<h2>REX_VALUE[1]</h2>`

notiert.

**Comment by skerbis** [comment]
und warum? ,.. dann macht man doch n normales Textfeld für die Abfrage. Hier sehe ich nun wirklich keinen Sinn für den WYSIWYG.

**Comment by alexwenz** [comment]
Siehe: https://github.com/FriendsOfREDAXO/tinymce/issues/59#issuecomment-1535774865

**Comment by skerbis** [comment]
ist aber nicht der Zweckt dieses Editors. Es ist nun mal n HTML-Editor.

**Comment by alexwenz** [comment]
Verstehe ich gerade nicht: die Eingabe wird doch in HTML umgesetzt. 

Wie gehst Du denn z.B. vor, wenn Du eine Überschrift eines Moduls in einer barrierefreien Webseite mit einem lang-Attribut im Span für ein verwendetes englisches Wort versehen möchtest?

**Comment by skerbis** [comment]
Xoutputfilter nutzen und solche Worte dort pflegen

**Comment by eaCe** [comment]
Frage, ist das wirklich ein Issue? Das liegt beim Vendor, oder sehe ich das falsch?

**Comment by dergel** [comment]
ich werde erstmal die vorhandenen Issues entfernen und einen Stand fertigstellen, mit welchem man ein Release machen kann. Im Moment ist die aktuelle Version von tinymce 6.8.3 .. deswegen verhält sich vielleicht auch einiges schon anders
