### ISSUE TITLE
Tiny 2x als AddOn

### ISSUE THREAD

**Issue by mbodon** [FriendsOfREDAXO/tinymce#83]
unter https://redaxo.org/download/addons/tags/?q=tiny taucht der Tiny 2x auf … etwas verwirrend ;-) und der Link zu GitHub ist bei beiden auch noch identisch auf Tiny 6

**Comment by skerbis** [comment]
Die AddOns wurden zusammengeführt. Daher gibt es "noch" 2 Einträge.

**Comment by alxndr-w** [comment]
Eine Info im Installer und auf der Website, welcher Key deprecated ist, wäre sinnvoll. Unter tinymce5 bekommt man nicht mit, dass es ein Upgrade gibt.
