### ISSUE TITLE
Fatal Error bie Update von Version 6.0.0-beta1 auf 6.1.0-beta1

### ISSUE THREAD

**Issue by TobiasKrais** [FriendsOfREDAXO/tinymce#87]
REDAXO: **InvalidArgumentException:** Folder "/public_html/rex-dev/redaxo/src/addons/tinymce/assets/scripts/tinymce/plugins/link_yform" not found!
**File:** redaxo/src/core/lib/util/finder.php
**Line:** 53

<details>
<summary>Stacktrace</summary>

| Function                                | File                                                       | Line     |
| --------------------------------------- | ---------------------------------------------------------- | -------- |
| rex_finder::factory                     | redaxo/src/core/lib/util/dir.php                           | 78       |
| rex_dir::copy                           | redaxo/src/addons/.new.tinymce/update.php                  | 26       |
| require                                 | redaxo/src/core/lib/packages/package.php                   | 233      |
| rex_package->includeFile                | redaxo/src/addons/install/lib/package/package_update.php   | 64       |
| rex_install_package_update->doAction    | redaxo/src/addons/install/lib/package/package_download.php | 47       |
| rex_install_package_download->run       | redaxo/src/addons/install/lib/api/api_package_update.php   | 24       |
| rex_api_install_package_update->execute | redaxo/src/core/lib/api_function.php                       | 197      |
| rex_api_function::handleCall            | redaxo/src/core/backend.php                                | 249      |
| require                                 | redaxo/src/core/boot.php                                   | 157      |
| require                                 | redaxo/index.php                                           | 9        |

</details>
<details>
<summary>System report (REDAXO 5.17.0, PHP 8.2.10-2ubuntu1, MySQL 8.0.36)</summary>

| REDAXO        |            |
| ------------: | :--------- |
|       Version | 5.17.0     |

</details>

**Comment by TobiasKrais** [comment]
Workaround: Addon deinstallieren und neu installieren

**Comment by alxndr-w** [comment]
Vermutlich `__FILE___` verwenden, damit der temporäre Addon-Ordner gefunden wird.

**Comment by TobiasKrais** [comment]
Warum werden die Assets überhaupt manuell kopiert? Ich dachte das läuft beim Update automatisch?

**Comment by alxndr-w** [comment]
Da bin ich mir auch ziemlich sicher, es sei denn, es würde dabei die Verzeichnisstruktur geändert.

Vielleicht ein Überbleibsel aus R4-Zeiten, nie infrage gestellt? Bis vor 1-2 Jahren gab es dazu auch keine Fehlermeldung. Ich denke, der Code war dazu einige Zeit lang "tot" ohne Meldung.

Schmeiß' raus :)

**Comment by TobiasKrais** [comment]
Hab die Zeilen entfernt und es getestet. Der Code nicht in der Tat nicht nötig. Commit ging direkt in den main branch.

**Comment by alxndr-w** [comment]
> Ich würde mir dann immer die Datei-Historie ansehen. Da erkennt man recht schnell, was einmal aufgenommen oder wann gelöscht wurde.

Dann könnte man ja auch Mal Bescheid geben, wenn man das sowieso weiß.

**Comment by tbaddade** [comment]
> Dann könnte man ja auch Mal Bescheid geben, wenn man das sowieso weiß.

Ich erspare uns das hier beiden.

**Comment by TobiasKrais** [comment]
Hab einen PR erstellt. Wäre der für euch OK?
